import tseslint from 'typescript-eslint';

const platformBans = [
  { group: ['node:*'], message: 'Platform-pure module: node:* is banned (see spec 4.5).' },
  { group: ['cloudflare:*'], message: 'Platform-pure module: cloudflare:* is banned (see spec 4.5).' },
  { group: ['hono', 'hono/*'], message: 'Platform-pure module: hono is banned (see spec 4.5).' },
];

export default tseslint.config(
  // worker-configuration.d.ts is generated by `wrangler types`, not authored here.
  { ignores: ['dist/**', '.wrangler/**', 'node_modules/**', 'coverage/**', 'worker-configuration.d.ts'] },
  ...tseslint.configs.recommended,
  {
    files: ['src/**/*.ts'],
    rules: { 'no-console': 'error' },
  },
  {
    files: ['src/obs/**/*.ts'],
    rules: { 'no-console': 'off' },
  },
  {
    files: ['src/core/**/*.ts', 'src/render/**/*.ts'],
    rules: { 'no-restricted-imports': ['error', { patterns: platformBans }] },
  },
);
